### ISSUE TITLE
Only plays one song at a time

### ISSUE THREAD

**Issue by lkellar** [puffyboa/audiovisual_v2#2]
Despite that the user selects a folder of music to play from, implying that the visualizer will play multiple songs, it doesn't. Could you either have individual song selection or have it play multiple songs?

**Comment by jpsank** [comment]
As of [now](https://github.com/puffyboa/audiovisual_v2/commit/cb7a01d3c8693ff045e8d146edc3cab036052ce9), the README has been updated to include the control TAB, which plays next song
